# Generated by Django 5.0.3 on 2024-03-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='upvotes',
            field=models.IntegerField(default=0),
        ),
    ]
