# Generated by Django 5.0.3 on 2024-03-21 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evApp', '0007_comment_reply_upvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='evApp.listing'),
            preserve_default=False,
        ),
    ]
