# Generated by Django 5.0.3 on 2024-03-21 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evApp', '0008_comment_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=40),
        ),
    ]
