# Generated by Django 5.0.3 on 2024-03-21 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evApp', '0009_alter_listing_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
