# Generated by Django 5.0.3 on 2024-03-26 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evApp', '0011_alter_upvote_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upvote',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='evApp.comment'),
        ),
    ]
