# Generated by Django 5.0.3 on 2024-03-26 15:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evApp', '0014_alter_reply_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='imageURL',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
